version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    image: api:dev
    ports:
      - "5000:5000"
    volumes:
      - .:/api
      - ./api/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    image: client:prod
    ports:
      - "3000:3000"
    volumes:
      - .:/client